-- MySQL Script generated by MySQL Workbench
-- 03/30/15 22:33:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema web_accessible_uml
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web_accessible_uml
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web_accessible_uml` DEFAULT CHARACTER SET utf8 ;
USE `web_accessible_uml` ;

-- -----------------------------------------------------
-- Table `web_accessible_uml`.`TipoDiagrama`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_accessible_uml`.`TipoDiagrama` (
  `id` BIGINT NOT NULL AUTO_INCREMENT AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `web_accessible_uml`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_accessible_uml`.`Usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `senha` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `web_accessible_uml`.`Diagrama`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_accessible_uml`.`Diagrama` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `idTipoDiagrama` BIGINT NOT NULL,
  `idUsuario` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Diagrama_TipoDiagrama_FK` (`idTipoDiagrama` ASC),
  INDEX `Diagrama_Usuario_FK` (`idUsuario` ASC),
  CONSTRAINT `Diagrama_TipoDiagrama_FK`
    FOREIGN KEY (`idTipoDiagrama`)
    REFERENCES `web_accessible_uml`.`TipoDiagrama` (`id`),
  CONSTRAINT `Diagrama_Usuario_FK`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `web_accessible_uml`.`Usuario` (`id`));


-- -----------------------------------------------------
-- Table `web_accessible_uml`.`Ator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_accessible_uml`.`Ator` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `x` FLOAT NULL DEFAULT NULL,
  `y` FLOAT NULL DEFAULT NULL,
  `largura` FLOAT NULL DEFAULT NULL,
  `altura` FLOAT NULL DEFAULT NULL,
  `idDiagrama` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Ator_Diagrama_FK` (`idDiagrama` ASC),
  CONSTRAINT `Ator_Diagrama_FK`
    FOREIGN KEY (`idDiagrama`)
    REFERENCES `web_accessible_uml`.`Diagrama` (`id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `web_accessible_uml`.`ElementoRelacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_accessible_uml`.`ElementoRelacao` (
  `tipoElemento` VARCHAR(50) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `web_accessible_uml`.`Ator_ElementoRelacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_accessible_uml`.`Ator_ElementoRelacao` (
  `idAtor` BIGINT NOT NULL,
  `idElementoRelacao` BIGINT NOT NULL,
  PRIMARY KEY (`idAtor`, `idElementoRelacao`),
  INDEX `ElementoRelacao_FK_2` (`idElementoRelacao` ASC),
  CONSTRAINT `Ator_FK`
    FOREIGN KEY (`idAtor`)
    REFERENCES `web_accessible_uml`.`Ator` (`id`),
  CONSTRAINT `ElementoRelacao_FK_2`
    FOREIGN KEY (`idElementoRelacao`)
    REFERENCES `web_accessible_uml`.`ElementoRelacao` (`id`));


-- -----------------------------------------------------
-- Table `web_accessible_uml`.`CasoDeUso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_accessible_uml`.`CasoDeUso` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `x` FLOAT NULL DEFAULT NULL,
  `y` FLOAT NULL DEFAULT NULL,
  `largura` FLOAT NULL DEFAULT NULL,
  `altura` FLOAT NULL DEFAULT NULL,
  `idDiagrama` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `CasoDeUso_Diagrama_FK` (`idDiagrama` ASC),
  CONSTRAINT `CasoDeUso_Diagrama_FK`
    FOREIGN KEY (`idDiagrama`)
    REFERENCES `web_accessible_uml`.`Diagrama` (`id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `web_accessible_uml`.`CasoDeUso_ElementoRelacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_accessible_uml`.`CasoDeUso_ElementoRelacao` (
  `idCasoDeUso` BIGINT NOT NULL,
  `idElementoRelacao` BIGINT NOT NULL,
  PRIMARY KEY (`idCasoDeUso`, `idElementoRelacao`),
  INDEX `ElementoRelacao_FK_1` (`idElementoRelacao` ASC),
  CONSTRAINT `CasoDeUso_FK`
    FOREIGN KEY (`idCasoDeUso`)
    REFERENCES `web_accessible_uml`.`CasoDeUso` (`id`),
  CONSTRAINT `ElementoRelacao_FK_1`
    FOREIGN KEY (`idElementoRelacao`)
    REFERENCES `web_accessible_uml`.`ElementoRelacao` (`id`));


-- -----------------------------------------------------
-- Table `web_accessible_uml`.`TipoRelacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_accessible_uml`.`TipoRelacao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `web_accessible_uml`.`Relacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_accessible_uml`.`Relacao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cardinalidadeOrigem` VARCHAR(10) NULL DEFAULT NULL,
  `cardinalidadeDestino` VARCHAR(10) NULL DEFAULT NULL,
  `idTipoRelacao` BIGINT NOT NULL,
  `idElementoOrigem` BIGINT NOT NULL,
  `idElementoDestino` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Relacao_ElementoDestino_FK` (`idElementoDestino` ASC),
  INDEX `Relacao_ElementoOrigem_FK` (`idElementoOrigem` ASC),
  INDEX `Relacao_TipoRelacao_FK` (`idTipoRelacao` ASC),
  CONSTRAINT `Relacao_ElementoDestino_FK`
    FOREIGN KEY (`idElementoDestino`)
    REFERENCES `web_accessible_uml`.`ElementoRelacao` (`id`),
  CONSTRAINT `Relacao_ElementoOrigem_FK`
    FOREIGN KEY (`idElementoOrigem`)
    REFERENCES `web_accessible_uml`.`ElementoRelacao` (`id`),
  CONSTRAINT `Relacao_TipoRelacao_FK`
    FOREIGN KEY (`idTipoRelacao`)
    REFERENCES `web_accessible_uml`.`TipoRelacao` (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `web_accessible_uml`.`TipoDiagrama`
-- -----------------------------------------------------
START TRANSACTION;
USE `web_accessible_uml`;
INSERT INTO `web_accessible_uml`.`TipoDiagrama` (`nome`) VALUES ('Caso de Uso');
INSERT INTO `web_accessible_uml`.`TipoDiagrama` (`nome`) VALUES ('Classe');

COMMIT;


-- -----------------------------------------------------
-- Data for table `web_accessible_uml`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `web_accessible_uml`;
INSERT INTO `web_accessible_uml`.`Usuario` (`nome`, `senha`) VALUES ('Leandro Luque', '123');
INSERT INTO `web_accessible_uml`.`Usuario` (`nome`, `senha`) VALUES ('Leandro Luque', '123');
INSERT INTO `web_accessible_uml`.`Usuario` (`nome`, `senha`) VALUES ('Leandro', '123');

COMMIT;


-- -----------------------------------------------------
-- Data for table `web_accessible_uml`.`TipoRelacao`
-- -----------------------------------------------------
START TRANSACTION;
USE `web_accessible_uml`;
INSERT INTO `web_accessible_uml`.`TipoRelacao` (`nome`) VALUES ('Comunicacao');
INSERT INTO `web_accessible_uml`.`TipoRelacao` (`nome`) VALUES ('Include');
INSERT INTO `web_accessible_uml`.`TipoRelacao` (`nome`) VALUES ('Extend');

COMMIT;

